Repository realm/realm-object-store, pull requests merged in 2018-10, with the labels that each got.

#695 Fix compilation with sync 3.11.1
  src/sync/sync_config.cpp
Labels: T:Internal

#534 Batch update for Results
  README.md
  src/object.cpp
  src/object.hpp
  src/object_accessor.hpp
  src/results.cpp
  src/results.hpp
  tests/results.cpp
Labels: T:Feature

#701 Add support for creating a subscription object immediately
  src/object_store.cpp
  src/sync/partial_sync.cpp
  src/sync/partial_sync.hpp
  tests/sync/partial_sync.cpp
Labels: T:Enhancement

#699 Initial implementation of diff-only update of objects
  src/impl/object_accessor_impl.hpp
  src/list.hpp
  src/object.hpp
  src/object_accessor.hpp
  src/results.hpp
  tests/object.cpp
Labels: T:Feature
