Repository realm/realm-object-store, pull requests merged in 2019-08, with the labels that each got.

#811 Adding check for cache_new_realm
  src/shared_realm.cpp
Labels: T:Bug-Crash

#675 Several tests updated
  tests/primitive_list.cpp
  tests/realm.cpp
  tests/transaction_log_parsing.cpp
Labels: T:Test

#815 Fix the check for if the ResultSets schema needs to be initialized
  src/sync/partial_sync.cpp
Labels: T:Bug

#824 Allows changing url_prefix of a created sync session
  src/sync/sync_config.hpp
  src/sync/sync_session.cpp
  src/sync/sync_session.hpp
Labels: T-Internal

#827 Use core's new fifo functions
  dependencies.list
  src/CMakeLists.txt
  src/impl/apple/external_commit_helper.cpp
  src/impl/epoll/external_commit_helper.cpp
  src/shared_realm.cpp
  src/util/fifo.cpp
  src/util/fifo.hpp
  workflow/test_coverage.sh
Labels: T-Enhancement
