Repository realm/realm-object-store, pull requests merged in 2019-03, with the labels that each got.

#774 Add has_existing_sessions()
  src/sync/sync_manager.cpp
  src/sync/sync_manager.hpp
  tests/sync/sync_manager.cpp
Labels: T:Enhancement

#760 Import the global notifier and adapter from realm-js-private
  CMakeLists.txt
  external/json/json.hpp
  src/CMakeLists.txt
  src/server/adapter.cpp
  src/server/adapter.hpp
  src/server/admin_realm.cpp
  src/server/admin_realm.hpp
  src/server/global_notifier.cpp
  src/server/global_notifier.hpp
  src/sync/sync_manager.cpp
  src/sync/sync_manager.hpp
  src/util/event_loop_dispatcher.hpp
  tests/sync/sync_manager.cpp
  workflow/build.sh
Labels: T:Internal

#775 Add support for Subscription timestamps and automatic cleanup
  src/sync/partial_sync.cpp
  src/sync/partial_sync.hpp
  tests/sync/partial_sync.cpp
Labels: T:Enhancement

#779 Reset status flag when updating subscription
  src/sync/partial_sync.cpp
  src/sync/partial_sync.hpp
  tests/sync/partial_sync.cpp
Labels: T:Bug

#781 Fix unsubscribing from a subscription which hasn't been created yet
  src/sync/partial_sync.cpp
  tests/sync/partial_sync.cpp
Labels: T:Bug-Crash
