Repository realm/realm-object-store, pull requests merged in 2019-11, with the labels that each got.

#869 Fix build error on Windows
  src/sync/sync_session.cpp
Labels: T-Internal

#874 Add support for creating a sync session manually
  src/impl/realm_coordinator.cpp
  src/impl/realm_coordinator.hpp
Labels: T-Enhancement

#875 Fix a rare notification-related deadlock
  src/impl/realm_coordinator.cpp
Labels: T-Bug

#867 Properly propagate update_only_diff through List::assign()
  src/impl/object_accessor_impl.hpp
  src/list.hpp
  src/object.hpp
  src/object_accessor.hpp
  src/results.hpp
  src/sync/sync_permission.cpp
  tests/migrations.cpp
  tests/object.cpp
  tests/sync/metadata.cpp
  tests/sync/permission.cpp
Labels: T-Bug

#877 Add some missing things to ResultsNotifier::release_data()
  src/impl/results_notifier.cpp
  tests/realm.cpp
Labels: T-Bug

#856 Add support for frozen objects
  src/impl/realm_coordinator.cpp
  src/impl/realm_coordinator.hpp
  src/list.cpp
  src/list.hpp
  src/object.cpp
  src/object.hpp
  src/results.cpp
  src/results.hpp
  src/shared_realm.cpp
  src/shared_realm.hpp
  tests/CMakeLists.txt
  tests/frozen_objects.cpp
  tests/realm.cpp
  tests/results.cpp
  tests/util/test_utils.cpp
Labels: T-Enhancement

#882 Update to sync v4.9.0
  dependencies.list
  src/sync/sync_config.hpp
  src/sync/sync_session.cpp
Labels: T-Internal

#883 Add tooling for Visual Studio Code
  .vscode/cmake-variants.yaml
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  tests/CMakeLists.txt
Labels: T-Internal
