Repository realm/realm-object-store, pull requests merged in 2019-09, with the labels that each got.

#837 Make ClientResyncMode an unsigned char
  src/sync/sync_config.hpp
Labels: T-Internal

#823 Port server components to core 6
  src/server/adapter.cpp
  src/server/admin_realm.cpp
  src/server/admin_realm.hpp
  src/server/global_notifier.cpp
  src/server/global_notifier.hpp
Labels: T-Feature

#843 Fix check for if the partial sync schema needs to be initialized
  src/sync/partial_sync.cpp
Labels: T-Bug-Crash

#842 Fix a crash when an observed primitive list is deleted before the first run of the notifier
  src/impl/primitive_list_notifier.cpp
  tests/list.cpp
  tests/primitive_list.cpp
Labels: T-Bug-Crash

#850 Replace the Adapter regex filter with a predicate function
  src/server/adapter.cpp
  src/server/adapter.hpp
Labels: T-Enhancement

#849 Add work-around for Java schema bug
  src/impl/realm_coordinator.cpp
Labels: T-Bug-Crash
