Repository realm/realm-object-store, pull requests merged in 2019-06, with the labels that each got.

#676 Je/list test
  Jenkinsfile
  dependencies.list
  src/results.cpp
  tests/list.cpp
  tests/object.cpp
  tests/results.cpp
  tests/transaction_log_parsing.cpp
Labels: T:Test

#802 Only use state transfer for async open on full sync Realms
  src/impl/realm_coordinator.cpp
  tests/realm.cpp
Labels: T:Bug

#804 Handle EINTR in the apple version of ExternalCommitHelper
  src/impl/apple/external_commit_helper.cpp
Labels: T:Bug

#803 Add support for Async Open
  src/CMakeLists.txt
  src/impl/realm_coordinator.cpp
  src/impl/realm_coordinator.hpp
  src/shared_realm.cpp
  src/shared_realm.hpp
  src/sync/async_open_task.cpp
  src/sync/async_open_task.hpp
  tests/realm.cpp
Labels: T:Enhancement

#805 Update protocol error for sync 4.6.0
  dependencies.list
  src/sync/sync_session.cpp
Labels: T:Internal

#806 Fix some async open issues
  src/impl/realm_coordinator.cpp
  src/impl/realm_coordinator.hpp
  src/impl/weak_realm_notifier.cpp
  src/impl/weak_realm_notifier.hpp
  src/shared_realm.cpp
  src/shared_realm.hpp
  src/sync/async_open_task.cpp
  src/sync/async_open_task.hpp
  src/sync/impl/sync_file.cpp
  src/sync/impl/sync_file.hpp
  src/sync/partial_sync.cpp
  src/sync/partial_sync.hpp
  src/sync/sync_session.cpp
  src/thread_safe_reference.hpp
  src/util/event_loop_dispatcher.hpp
  tests/realm.cpp
  tests/sync/permission.cpp
  tests/sync/session/session.cpp
Labels: T:Bug
