Repository realm/realm-object-store, pull requests merged in 2020-02, with the labels that each got.

#907 Remove sync history validation
  src/impl/realm_coordinator.cpp
  src/impl/realm_coordinator.hpp
  src/sync/sync_config.hpp
  src/sync/sync_session.cpp
Labels: T-Internal

#910 Fix thread-safety issues with frozen Results
  CMake/CompilerFlags.cmake
  src/CMakeLists.txt
  src/execution_context_id.hpp
  src/impl/collection_notifier.cpp
  src/impl/collection_notifier.hpp
  src/impl/realm_coordinator.cpp
  src/impl/realm_coordinator.hpp
  src/list.cpp
  src/list.hpp
  src/object.cpp
  src/object.hpp
  src/object_accessor.hpp
  src/object_schema.cpp
  src/object_schema.hpp
  src/property.hpp
  src/results.cpp
  src/results.hpp
  src/schema.cpp
  src/schema.hpp
  src/util/checked_mutex.hpp
  src/util/copyable_atomic.hpp
  src/util/tagged_bool.hpp
  tests/util/test_file.cpp
Labels: T-Bug

#921 Realm App
  Dockerfile
  external/json/json.hpp
  src/CMakeLists.txt
  src/server/global_notifier.cpp
  src/sync/app.cpp
  src/sync/app.hpp
  src/sync/app_credentials.cpp
  src/sync/app_credentials.hpp
  src/sync/generic_network_transport.cpp
  src/sync/generic_network_transport.hpp
  src/sync/impl/sync_metadata.cpp
  src/sync/impl/sync_metadata.hpp
  src/sync/sync_manager.cpp
  src/sync/sync_manager.hpp
  src/sync/sync_user.cpp
  src/sync/sync_user.hpp
  tests/CMakeLists.txt
  tests/sync/app.cpp
  tests/sync/file.cpp
  tests/sync/metadata.cpp
  tests/sync/partial_sync.cpp
  tests/sync/permission.cpp
  tests/sync/session/connection_change_notifications.cpp
  tests/sync/session/session.cpp
  tests/sync/session/wait_for_completion.cpp
  tests/sync/sync_manager.cpp
  tests/sync/user.cpp
  tests/util/test_file.cpp
  tests/util/test_file.hpp
  tests/util/test_utils.cpp
  tests/util/test_utils.hpp
Labels: Blocked
